Repository yourssu/YDS-Android, pull requests merged in 2024-02, with the labels that each got.

#249 [YDS-#248] Improve : SingleTopBar, DoubleTopBar 네비게이션 아이콘 넣을 수 있게
  compose/src/main/java/com/yourssu/design/system/compose/atom/TopBarButton.kt
  compose/src/main/java/com/yourssu/design/system/compose/base/YdsScaffold.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/BottomBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/DoubleTitleTopBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/SearchTopBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/SingleTitleTopBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/TopBar.kt
  version.properties
Labels: enhancement, yds-compose

#252 [YDS-#245] Hotfix : jdk11 -> jdk17
  compose/build.gradle.kts
  jitpack.yml
  version.properties
Labels: bug, help wanted

#256 [YDS-#255] ydsClickable 개선
  .github/pull_request_template.md
  compose/src/main/java/com/yourssu/design/system/compose/base/YdsClickable.kt
  version.properties
Labels: improvement

#258 [YDS-#257] YdsText에 overflow 및 maxLines 속성 추가
  compose/src/main/java/com/yourssu/design/system/compose/base/YdsText.kt
  version.properties
Labels: enhancement
