Repository yourssu/YDS-Android, pull requests merged in 2024-01, with the labels that each got.

#233 [YDS-#228] Component - Toast 구현
  compose/src/main/java/com/yourssu/design/system/compose/atom/Badge.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/BottomSheet.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/BoxButton.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/CheckBox.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/Divider.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/ListItem.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/ListToggleItem.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/PasswordTextField.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/Picker.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/PlainButton.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/ProfileImageView.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/SimpleTextField.kt
  compose/src/main/java/com/yourssu/design/system/compose/atom/Toggle.kt
  compose/src/main/java/com/yourssu/design/system/compose/base/YdsScaffold.kt
  compose/src/main/java/com/yourssu/design/system/compose/base/YdsText.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/toast/Toast.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/toast/ToastAnimation.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/toast/ToastHost.kt
  version.properties
Labels: feature

#241 [YDS-#240] Component - BottomBar
  compose/build.gradle.kts
  compose/src/main/java/com/yourssu/design/system/compose/component/BottomBar.kt
  compose/src/main/res/drawable/ic_board_filled.xml
  compose/src/main/res/drawable/ic_board_line.xml
  compose/src/main/res/drawable/ic_calendar_filled.xml
  compose/src/main/res/drawable/ic_calendar_line.xml
  compose/src/main/res/drawable/ic_home_filled.xml
  compose/src/main/res/drawable/ic_home_line.xml
  compose/src/main/res/drawable/ic_person_filled.xml
  compose/src/main/res/drawable/ic_person_line.xml
  compose/src/main/res/drawable/ic_rank_filled.xml
  compose/src/main/res/drawable/ic_rank_line.xml
  version.properties
Labels: feature

#242 [Improve] TopAppBar 제작
  compose/src/main/java/com/yourssu/design/system/compose/base/YdsScaffold.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/BottomBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/DoubleTitleTopBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/SearchTopBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/SingleTitleTopBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/TopAppBar.kt
  compose/src/main/java/com/yourssu/design/system/compose/component/topbar/TopBar.kt
  version.properties
Labels: improvement

#243 [YDS-#195] improve : gradle 버전 / JDK version update
  .github/workflows/buildTest.yml
  .github/workflows/deployDevStoryBook.yml
  .github/workflows/deployLibraryYDS.yml
  DesignSystem/build.gradle
  DesignSystem/src/main/AndroidManifest.xml
  app/storybook/build.gradle
  app/storybook/src/main/AndroidManifest.xml
  app/yds-ui-tester/build.gradle
  app/yds-ui-tester/src/main/AndroidManifest.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  version.properties
Labels: improvement

#244 [YDS] doc: PR 템플릿 추가
  .github/pull_request_template.md
Labels: skip
